on: 
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branch:
      - 'master'

name: Release Package With Version

jobs:
  build:
    runs-on: windows-latest
    env:
      EXE_NAME: AutoTFT
      RELEASE_PACKAGE_NAME: AutoTFT
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install opencv-python
          pip install pyautogui
          pip install keyboard
          pip install pywin32

      - name: Generate Requirements
        run : |
          pip freeze > requirements.txt

      - name: Upload Requirements
        uses: actions/upload-artifact@v2
        with:
          name: requirements
          path: requirements.txt

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v2
      #   with: 
      #     name: LOL_report_tool.zip
      #     path: LOL_report_tool.zip
      #     retention-days: 7

      # TODO: pack the exe and images in a zip and release it
      
      # Install dep via requirements.txt
      # pip install -r requirements.txt
